networks:
  traefik:
    name: traefik

# We add a Docker secret to store the users for Basic Auth
secrets:
  auth_users:
    file: ./secrets/auth-users.txt

services:
  traefik:
    image: traefik:${TRAEFIK_IMAGE_VERSION:-latest}
    command:
      ## Global
      # Uncomment next line when testing
      # - --log.level=DEBUG
      # No more need to add --api.insecure=true as we access Traefik only using its domain name
      - --api.dashboard=true
      ## Docker
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      ## Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      ## Certificates
      # We add Let's Encrypt as a default certificate resolver
      # Uncomment next line when testing
      # - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    # We add the usage of secrets for Basic Auth
    secrets:
      - auth_users
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## Middlewares
      # We add a Basic Auth middleware using the users defined in the Docker secret
      - traefik.http.middlewares.basic-auth.basicauth.usersFile=/run/secrets/auth_users
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      ## HTTP
      - traefik.http.routers.traefik-http.entrypoints=http
      - traefik.http.routers.traefik-http.rule=Host(`${TRAEFIK_DOMAIN_NAME}`)
      - traefik.http.routers.traefik-http.service=api@internal
      - traefik.http.routers.traefik-http.middlewares=redirect-to-https
      ## HTTPS
      - traefik.http.routers.traefik-https.entrypoints=https
      - traefik.http.routers.traefik-https.rule=Host(`${TRAEFIK_DOMAIN_NAME}`)
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.routers.traefik-https.middlewares=basic-auth
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.tls.certresolver=letsencrypt
