networks:
  traefik:
    name: traefik

secrets:
  auth_users:
    file: ./secrets/auth-users.txt

services:
  traefik:
    image: traefik:${TRAEFIK_IMAGE_VERSION:-latest}
    command:
      ## Global
      # Uncomment next line when testing
      # - --log.level=DEBUG
      - --api.dashboard=true
      ## Docker
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      ## Entrypoints
      - --entrypoints.http.address=:80
      # We redirect all HTTP traffic to HTTPS
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      - --entrypoints.https.address=:443
      # We enable TLS for all HTTPS traffic
      - --entrypoints.https.http.tls.certresolver=letsencrypt
      # We ask Let's Encrypt to generate certificates for our base domain and wildcard subdomain
      - --entrypoints.https.http.tls.domains[0].main=${TRAEFIK_BASE_DOMAIN_NAME}
      - --entrypoints.https.http.tls.domains[0].sans=*.${TRAEFIK_BASE_DOMAIN_NAME}
      ## Certificates
      # Uncomment next line when testing
      # - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # We switch to DNS-01 challenge to generate certificates
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=desec
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=30
    restart: unless-stopped
    environment:
      - DESEC_TOKEN=${TRAEFIK_DESEC_TOKEN}
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    secrets:
      - auth_users
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## Middlewares
      # No more need for the middleware to redirect HTTP to HTTPS
      - traefik.http.middlewares.basic-auth.basicauth.usersFile=/run/secrets/auth_users
      ## HTTP
      # No more need of the HTTP configuration as all HTTP traffic is redirected to HTTPS
      ## HTTPS
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN_NAME}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=basic-auth
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      # We ask Let's Encrypt to generate certificates for our base domain and wildcard subdomain
      - traefik.http.routers.traefik.tls.domains[0].main=${TRAEFIK_BASE_DOMAIN_NAME}
      - traefik.http.routers.traefik.tls.domains[0].sans=*.${TRAEFIK_BASE_DOMAIN_NAME}
