networks:
  traefik:
    external: true

services:
  whoami-without-stripprefix:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    networks:
      - traefik
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## HTTP
      - traefik.http.routers.whoami-without-stripprefix.entrypoints=http
      - traefik.http.routers.whoami-without-stripprefix.rule=Host(`localhost`) && PathPrefix(`/whoami-without-stripprefix`)

  whoami-with-stripprefix:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    networks:
      - traefik
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## Middlewares
      # We add a middleware to strip the prefix `/whoami-with-stripprefix` from the request
      - traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes=/whoami-with-stripprefix
      ## HTTP
      - traefik.http.routers.whoami-with-stripprefix.entrypoints=http
      - traefik.http.routers.whoami-with-stripprefix.rule=Host(`localhost`) && PathPrefix(`/whoami-with-stripprefix`)
      # We add the middleware created above in the middleware chain of this router
      - traefik.http.routers.whoami-with-stripprefix.middlewares=whoami-stripprefix
