networks:
  traefik:
    name: traefik

services:
  whoami:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    networks:
      - traefik
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## HTTP
      # No more need of the HTTP configuration as all HTTP traffic is redirected to HTTPS
      ## HTTPS
      # No mode need to set the TLS resolver here, as we are using wildcard certificates
      - traefik.http.routers.whoami.entrypoints=https
      - traefik.http.routers.whoami.rule=Host(`${WHOAMI_DOMAIN_NAME}`)
      - traefik.http.routers.whoami.tls=true
