networks:
  traefik:
    external: true

services:
  whoami:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    networks:
      - traefik
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik
      ## HTTP
      - traefik.http.routers.whoami-http.entrypoints=http
      - traefik.http.routers.whoami-http.rule=Host(`${WHOAMI_DOMAIN_NAME}`)
      # We add a middleware to redirect HTTP to HTTPS
      - traefik.http.routers.whoami-http.middlewares=redirect-to-https
      ## HTTPS
      # We add the HTTPS configuration
      - traefik.http.routers.whoami-https.entrypoints=https
      - traefik.http.routers.whoami-https.rule=Host(`${WHOAMI_DOMAIN_NAME}`)
      - traefik.http.routers.whoami-https.tls=true
      - traefik.http.routers.whoami-https.tls.certresolver=letsencrypt
